import { useState, useCallback } from "react";
import MonacoEditor from "@monaco-editor/react";
import "./PythonPanel.css";

interface PythonPanelProps {
  code: string;
}

export default function PythonPanel({ code }: PythonPanelProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = code;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  }, [code]);

  if (!code) {
    return (
      <div className="python-panel">
        <div className="python-panel__empty">
          <div>🐍</div>
          <div>Code chalao to Python code generate hoga</div>
        </div>
      </div>
    );
  }

  return (
    <div className="python-panel" id="python-panel">
      <div className="python-panel__header">
        <div className="python-panel__header-left">
          🐍 Generated Python Code
        </div>
        <button
          className={`python-panel__copy-btn ${
            copied ? "python-panel__copy-btn--copied" : ""
          }`}
          onClick={handleCopy}
          id="copy-python-btn"
        >
          {copied ? "✓ Copied!" : "📋 Copy"}
        </button>
      </div>

      <div className="python-panel__editor">
        <MonacoEditor
          height="100%"
          language="python"
          theme="vs-dark"
          value={code}
          options={{
            readOnly: true,
            fontSize: 14,
            fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
            minimap: { enabled: false },
            scrollBeyondLastLine: false,
            lineNumbers: "on",
            renderLineHighlight: "none",
            padding: { top: 12 },
            smoothScrolling: true,
            wordWrap: "on",
            automaticLayout: true,
          }}
        />
      </div>

      <div className="python-panel__footer">
        Generated by URDU-CUSTOM-COMPILER — ایک کسٹم زبان
      </div>
    </div>
  );
}
