"""
Urdu Custom Compiler — Python Code Generator
Converts AST directly into valid, runnable Python source code.
Maps Urdu keywords to their Python equivalents with proper indentation.
"""

from __future__ import annotations
from typing import List

from .parser import (
    ASTNode, NumberNode, StringNode, BoolNode, VarNode,
    BinOpNode, UnaryOpNode, AssignNode, PrintNode, IfNode, WhileNode,
    FuncDefNode, ReturnNode, FuncCallNode,
    ArrayLiteralNode, ArrayAccessNode, ArrayAssignNode,
    InputNode, TypeCastNode,
)


# Operator mapping from Urdu to Python
OP_MAP = {
    "aur": "and",
    "ya": "or",
}


class CodeGenerator:
    """
    Converts AST into valid Python source code.

    Usage:
        python_code = CodeGenerator().generate(ast_nodes)
    """

    def __init__(self) -> None:
        self._lines: List[str] = []
        self._indent_level = 0
        self._indent_str = "    "  # 4 spaces

    def generate(self, ast_nodes: List[ASTNode]) -> str:
        """Generate complete Python source from AST nodes."""
        self._lines = []
        self._indent_level = 0

        # Add header comment
        self._lines.append("# Generated by URDU-CUSTOM-COMPILER")
        self._lines.append("# Urdu --> Python transpilation")
        self._lines.append("")

        for node in ast_nodes:
            self._gen_stmt(node)

        return "\n".join(self._lines)

    # ── Helpers ──

    def _emit_line(self, line: str) -> None:
        """Emit a single line with current indentation."""
        prefix = self._indent_str * self._indent_level
        self._lines.append(f"{prefix}{line}")

    def _indent(self) -> None:
        """Increase indentation level."""
        self._indent_level += 1

    def _dedent(self) -> None:
        """Decrease indentation level."""
        self._indent_level = max(0, self._indent_level - 1)

    # ── Statement generation ──

    def _gen_stmt(self, node: ASTNode) -> None:
        """Generate Python code for a single statement."""
        if isinstance(node, AssignNode):
            expr_str = self._gen_expr(node.value_expr)
            self._emit_line(f"{node.name} = {expr_str}")

        elif isinstance(node, PrintNode):
            expr_str = self._gen_expr(node.expr)
            self._emit_line(f"print({expr_str})")

        elif isinstance(node, IfNode):
            cond_str = self._gen_expr(node.condition)
            self._emit_line(f"if {cond_str}:")
            self._indent()
            if node.body:
                for stmt in node.body:
                    self._gen_stmt(stmt)
            else:
                self._emit_line("pass")
            self._dedent()

            if node.else_body:
                self._emit_line("else:")
                self._indent()
                for stmt in node.else_body:
                    self._gen_stmt(stmt)
                self._dedent()

        elif isinstance(node, WhileNode):
            cond_str = self._gen_expr(node.condition)
            self._emit_line(f"while {cond_str}:")
            self._indent()
            if node.body:
                for stmt in node.body:
                    self._gen_stmt(stmt)
            else:
                self._emit_line("pass")
            self._dedent()

        elif isinstance(node, FuncDefNode):
            params = ", ".join(node.params)
            self._emit_line(f"def {node.name}({params}):")
            self._indent()
            if node.body:
                for stmt in node.body:
                    self._gen_stmt(stmt)
            else:
                self._emit_line("pass")
            self._dedent()
            self._lines.append("")  # blank line after function

        elif isinstance(node, ReturnNode):
            if node.value:
                val_str = self._gen_expr(node.value)
                self._emit_line(f"return {val_str}")
            else:
                self._emit_line("return")

        elif isinstance(node, FuncCallNode):
            args_str = ", ".join(self._gen_expr(a) for a in node.args)
            self._emit_line(f"{node.name}({args_str})")

        elif isinstance(node, ArrayAssignNode):
            idx_str = self._gen_expr(node.index)
            val_str = self._gen_expr(node.value)
            self._emit_line(f"{node.name}[{idx_str}] = {val_str}")

    # ── Expression generation ──

    def _gen_expr(self, node: ASTNode) -> str:
        """Generate Python expression string from an AST expression node."""
        if isinstance(node, NumberNode):
            return str(node.value)

        if isinstance(node, StringNode):
            # Escape quotes inside the string
            escaped = node.value.replace("\\", "\\\\").replace('"', '\\"')
            return f'"{escaped}"'

        if isinstance(node, BoolNode):
            return "True" if node.value else "False"

        if isinstance(node, VarNode):
            return node.name

        if isinstance(node, UnaryOpNode):
            operand = self._gen_expr(node.operand)
            return f"(-{operand})"

        if isinstance(node, BinOpNode):
            left = self._gen_expr(node.left)
            right = self._gen_expr(node.right)
            op = OP_MAP.get(node.op, node.op)
            return f"({left} {op} {right})"

        if isinstance(node, FuncCallNode):
            args_str = ", ".join(self._gen_expr(a) for a in node.args)
            return f"{node.name}({args_str})"

        if isinstance(node, ArrayLiteralNode):
            elems = ", ".join(self._gen_expr(e) for e in node.elements)
            return f"[{elems}]"

        if isinstance(node, ArrayAccessNode):
            arr = self._gen_expr(node.array)
            idx = self._gen_expr(node.index)
            return f"{arr}[{idx}]"

        if isinstance(node, InputNode):
            if node.prompt:
                prompt_str = self._gen_expr(node.prompt)
                return f"input({prompt_str})"
            return "input()"

        if isinstance(node, TypeCastNode):
            expr_str = self._gen_expr(node.expr)
            return f"{node.target_type}({expr_str})"

        return "None"
